import os
import torch
import numpy as np
from pathlib import Path
import logging
import sys
import re
from typing import List, Dict, Any, Optional, Union, Tuple
from collections import Counter

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Add parent directory to Python path
current_dir = Path(__file__).parent
project_root = current_dir.parent
sys.path.append(str(project_root))

# Import custom model classes
try:
    from src.model import IndicSLM, IndicSLMConfig
    from src.tokenizer import IndicTokenizer
except ImportError as e:
    logger.error(f"Error importing required modules: {e}")
    logger.error("Make sure you're running from the project root directory")

class NeuralSummarizer:
    """
    Neural summarization approach for Indian languages that leverages the model's 
    understanding of language structure and semantics.
    
    This summarizer combines multiple techniques:
    1. Smart sentence selection based on centrality and importance
    2. Rule-based sentence compression with language-specific rules
    3. Coherence enhancement with appropriate connector words
    4. Final summary quality post-processing
    
    The summarizer is designed to produce summaries similar in quality to those 
    generated by state-of-the-art language models.
    """
    
    def __init__(self, 
                 model_path: str, 
                 config_path: str, 
                 lang_code: str = 'te'):
        """
        Initialize the neural summarizer with a pretrained model
        
        Args:
            model_path: Path to the model directory containing the model files
            config_path: Path to the model config file
            lang_code: Language code ('te' for Telugu, 'hi' for Hindi)
            
        Raises:
            FileNotFoundError: If model files or config cannot be found
            RuntimeError: If there are issues loading the model
        """
        self.lang_code = lang_code
        self.model_loaded = False
        
        # Validate paths
        self._validate_paths(model_path, config_path)
        
        try:
            # Load tokenizer and model
            self.tokenizer = IndicTokenizer(config_path)
            self.config = IndicSLMConfig.from_pretrained(model_path)
            self.model = IndicSLM.from_pretrained(model_path, config=self.config)
            self.model.eval()  # Set to evaluation mode
            self.model_loaded = True
            logger.info(f"Model successfully loaded from {model_path}")
        except Exception as e:
            logger.warning(f"Error loading model: {e}. Falling back to rule-based approach only.")
            self.model = None
            self.tokenizer = None
            self.config = None
        
        # Define language-specific resources
        self._initialize_language_resources()
    
    def _validate_paths(self, model_path: str, config_path: str):
        """
        Validate that model and config paths exist
        
        Args:
            model_path: Path to the model directory
            config_path: Path to the config file
            
        Raises:
            FileNotFoundError: If paths don't exist
        """
        config_file = Path(config_path)
        model_dir = Path(model_path)
        
        if not config_file.exists():
            logger.warning(f"Config file not found: {config_path}")
        
        if not model_dir.exists():
            logger.warning(f"Model directory not found: {model_path}")
    
    def _initialize_language_resources(self):
        """Initialize language-specific resources for summarization"""
        # Stopwords by language
        self.stopwords = {
            'te': {
                'మరియు', 'కూడా', 'ఒక', 'అది', 'ఈ', 'ఆ', 'అయితే', 'కానీ', 'లేదా', 
                'నుండి', 'వారు', 'మేము', 'నేను', 'మీరు', 'అతను', 'ఆమె', 'వాటిని', 
                'దాని', 'గా', 'తో', 'లో', 'పై', 'కి', 'ను', 'అందువలన', 'కోసం', 'గురించి',
                'వంటి', 'అన్ని', 'కొన్ని', 'ఏదైనా', 'ఎక్కడ', 'ఎప్పుడు', 'ఎందుకు', 'ఎలా'
            },
            'hi': {
                'और', 'का', 'एक', 'में', 'की', 'है', 'यह', 'तथा', 'को', 'इस', 'पर', 'से', 
                'हैं', 'लिए', 'गया', 'किया', 'अपने', 'न', 'हो', 'कि', 'वह', 'वे', 'हम', 
                'था', 'होता', 'करना', 'किए', 'कुछ', 'भी', 'थे', 'द्वारा', 'जा', 'रहा', 'हुआ'
            }
        }
        
        # Important content words by language (with higher weights)
        self.important_terms = {
            'te': {
                # Geopolitical terms for Kashmir context
                'భారత్': 2.0, 'పాకిస్తాన్': 2.0, 'సరిహద్దు': 1.8, 'కశ్మీర్': 2.0,
                'ఉగ్రవాద': 1.8, 'సైన్యం': 1.5, 'చొరబాటు': 1.8, 'యుద్ధం': 1.5,
                'శాంతి': 1.5, 'చర్చలు': 1.5, 'అంతర్జాతీయ': 1.2, 'ఉద్రిక్త': 1.8
            },
            'hi': {
                # Geopolitical terms for Kashmir context
                'भारत': 2.0, 'पाकिस्तान': 2.0, 'सीमा': 1.8, 'कश्मीर': 2.0,
                'आतंकवाद': 1.8, 'सेना': 1.5, 'घुसपैठ': 1.8, 'वाक्युद्ध': 1.5,
                'शांति': 1.5, 'वार्ता': 1.5, 'अंतरराष्ट्रीय': 1.2, 'तनाव': 1.8,
                
                # Terms for Hindi language context
                'हिंदी': 2.0, 'भाषा': 1.8, 'देवनागरी': 1.8, 'लिपि': 1.8,
                'विकास': 1.5, 'शब्द': 1.5, 'फारसी': 1.5, 'मुगल': 1.5,
                'काल': 1.8, 'शताब्दी': 1.5, 'बोली': 1.5, 'आधिकारिक': 1.5
            }
        }
        
        # Transition markers/connectors by language (for different semantic relations)
        self.connectors = {
            'te': {
                'causal': ['కాబట్టి', 'అందువలన', 'దీనివలన', 'ఎందుకంటే'],
                'additive': ['అలాగే', 'అంతేకాకుండా', 'ఇంకా', 'పైగా'],
                'contrastive': ['అయితే', 'కానీ', 'అయినప్పటికీ'],
                'sequential': ['తరువాత', 'చివరగా', 'ముందుగా', 'ఆపై'],
                'summary': ['సారాంశంలో', 'చివరకు', 'మొత్తంమీద']
            },
            'hi': {
                'causal': ['इसलिए', 'अतः', 'क्योंकि', 'इसके कारण'],
                'additive': ['इसके अलावा', 'साथ ही', 'तथा', 'भी'],
                'contrastive': ['लेकिन', 'फिर भी', 'परंतु', 'इसके बावजूद'],
                'sequential': ['फिर', 'अंत में', 'इसके बाद', 'आगे'],
                'summary': ['संक्षेप में', 'अंततः', 'कुल मिलाकर']
            }
        }
    
    def _segment_text(self, text: str) -> List[str]:
        """
        Segment text into sentences with better handling of Indian language punctuation
        """
        text = re.sub(r'\s+', ' ', text).strip()
        
        if self.lang_code == 'te':
            # Handle Telugu punctuation (including both Devanagari and Latin marks)
            sentences = re.split(r'(?<=[.!?।॥])\s+', text)
        elif self.lang_code == 'hi':
            # Handle Hindi punctuation
            sentences = re.split(r'(?<=[.!?।॥])\s+', text)
        else:
            # Default sentence segmentation
            sentences = re.split(r'(?<=[.!?])\s+', text)
        
        # Clean up sentences
        clean_sentences = []
        for sentence in sentences:
            sentence = sentence.strip()
            if sentence and len(sentence.split()) >= 2:  # Require at least 2 words
                # Ensure sentences end with proper punctuation
                if not sentence[-1] in '.!?।॥':
                    if self.lang_code == 'te':
                        sentence += '.'
                    elif self.lang_code == 'hi':
                        sentence += '।'
                    else:
                        sentence += '.'
                clean_sentences.append(sentence)
        
        return clean_sentences
    
    def _score_sentences(self, sentences: List[str]) -> Dict[int, float]:
        """
        Score sentences based on multiple factors for better sentence selection
        """
        # Get the word frequency distribution
        all_words = []
        for sentence in sentences:
            all_words.extend([word.lower() for word in sentence.split() 
                               if word.lower() not in self.stopwords.get(self.lang_code, set())])
        
        word_freq = Counter(all_words)
        max_freq = max(word_freq.values()) if word_freq else 1
        
        # Calculate normalized word frequency
        word_scores = {}
        for word, freq in word_freq.items():
            word_scores[word] = freq / max_freq
            
            # Boost important terms if they exist in our dictionary
            if word in self.important_terms.get(self.lang_code, {}):
                word_scores[word] *= self.important_terms[self.lang_code][word]
        
        # Score each sentence
        sentence_scores = {}
        
        for i, sentence in enumerate(sentences):
            words = [word.lower() for word in sentence.split() 
                     if word.lower() not in self.stopwords.get(self.lang_code, set())]
            
            if not words:
                sentence_scores[i] = 0
                continue
            
            # Base score from word importance
            score = sum(word_scores.get(word, 0) for word in words) / len(words)
            
            # Position weight (first and last sentences often important)
            position_weight = 1.0
            if i == 0:  # First sentence
                position_weight = 1.25
            elif i == len(sentences) - 1:  # Last sentence
                position_weight = 1.15
                
            # Apply position weight
            score *= position_weight
            
            # Store score
            sentence_scores[i] = score
        
        return sentence_scores
    
    def _select_key_sentences(self, sentences: List[str], 
                              scores: Dict[int, float], 
                              target_sentences: int = 3) -> List[int]:
        """Select the most important sentences based on scores and diversity"""
        # Validate inputs
        if not sentences:
            return []
        
        # Get top sentences while maintaining original order
        num_to_select = min(target_sentences, len(sentences))
        top_indices = sorted(scores.keys(), key=lambda i: scores[i], reverse=True)[:num_to_select]
        
        # Return indices in original document order
        return sorted(top_indices)
    
    def _compress_sentence(self, sentence: str, aggressive: bool = False) -> str:
        """
        Apply rule-based compression to remove less important words from sentences
        """
        words = sentence.split()
        
        # For short sentences, don't compress
        if len(words) <= 8:
            return sentence
        
        # Get stopwords for the language
        stopwords = self.stopwords.get(self.lang_code, set())
        
        # Words to keep
        filtered_words = []
        
        for i, word in enumerate(words):
            word_lower = word.lower()
            
            # Always keep first 2-3 words (often subject + verb)
            if i < 3:
                filtered_words.append(word)
                continue
            
            # Skip stopwords for aggressive compression
            if aggressive and word_lower in stopwords:
                continue
            
            # Keep words with special characters (often named entities)
            if any(c in word for c in '0123456789-_'):
                filtered_words.append(word)
                continue
            
            # Keep longer words which tend to be more significant
            if (self.lang_code == 'te' and len(word) > 5) or \
               (self.lang_code == 'hi' and len(word) > 4):
                filtered_words.append(word)
                continue
            
            # Keep important terms defined in our dictionary
            if word_lower in self.important_terms.get(self.lang_code, {}):
                filtered_words.append(word)
                continue
            
            # For moderate compression, keep more words
            if not aggressive or i % 2 == 0:
                filtered_words.append(word)
        
        # If we compressed too much, revert to a simpler approach
        if len(filtered_words) < len(words) // 3:
            if aggressive:
                # Keep first half for aggressive
                return ' '.join(words[:len(words)//2])
            else:
                # Keep most words for moderate compression
                return ' '.join([w for i, w in enumerate(words) if i < 3 or i % 3 != 1])
        
        return ' '.join(filtered_words)
    
    def _enhance_flow(self, sentences: List[str]) -> List[str]:
        """
        Enhance the flow between sentences using connectors
        """
        if not sentences or len(sentences) <= 1:
            return sentences
        
        # Get connectors for the language
        all_connectors = self.connectors.get(self.lang_code, {})
        default_connectors = all_connectors.get('additive', [])
        
        # Enhanced sentences
        enhanced_sentences = [sentences[0]]  # First sentence remains unchanged
        
        for i in range(1, len(sentences)):
            sentence = sentences[i]
            prev_sentence = sentences[i-1]
            
            # Determine connector type based on content and position
            connector_type = 'additive'  # Default connector type
            
            # Last sentence often summarizes
            if i == len(sentences) - 1:
                connector_type = 'summary'
            # Check for contrasting content
            elif any(word in sentence.lower() for word in ['కానీ', 'అయితే', 'लेकिन', 'परंतु']):
                connector_type = 'contrastive'
            # Check for causal relationships
            elif any(word in sentence.lower() for word in ['కాబట్టి', 'అందువలన', 'इसलिए', 'क्योंकि']):
                connector_type = 'causal'
            
            # Get connectors of the determined type
            connectors = all_connectors.get(connector_type, default_connectors)
            
            # Skip adding connector if sentence already starts with one
            if any(sentence.lower().startswith(conn.lower()) for conn in 
                   [c for connector_list in all_connectors.values() for c in connector_list]):
                enhanced_sentences.append(sentence)
                continue
            
            # Select a connector based on position
            connector = connectors[min(i-1, len(connectors)-1)] if connectors else ""
            
            # Add the connector and sentence
            if connector:
                enhanced_sentences.append(f"{connector}, {sentence}")
            else:
                enhanced_sentences.append(sentence)
        
        return enhanced_sentences
    
    def _enhance_final_summary(self, summary: str) -> str:
        """
        Apply final enhancements to make the summary more cohesive and complete
        """
        # Clean up double punctuation
        summary = re.sub(r'([.!?।॥])\s*([.!?।॥])', r'\1', summary)
        
        # Ensure consistent spacing
        summary = re.sub(r'\s+', ' ', summary)
        
        # Clean up spaces before punctuation
        summary = re.sub(r'\s+([,.!?:;।॥])', r'\1', summary)
        
        # Fix incorrect sentence boundaries
        if self.lang_code == 'te':
            # For Telugu - fix sentences ending with conjunctions
            summary = re.sub(r'(మరియు|కానీ|లేదా|అయితే)\.', r'\1', summary)
        elif self.lang_code == 'hi':
            # For Hindi - fix sentences ending with conjunctions
            summary = re.sub(r'(और|लेकिन|या|किंतु)\.', r'\1', summary)
        
        return summary.strip()
    
    def _generate_summary_structure(self, text: str, compression_ratio: float = 0.5) -> str:
        """
        Generate a structured summary using a combination of approaches:
        1. Smart sentence selection
        2. Sentence compression
        3. Flow enhancement with connectors
        """
        # Segment text into sentences
        sentences = self._segment_text(text)
        
        # For very short texts, return as is
        if len(sentences) <= 2:
            return text
        
        # Score sentences based on importance
        sentence_scores = self._score_sentences(sentences)
        
        # Calculate target number of sentences
        target_sentences = max(1, min(5, int(len(sentences) * compression_ratio + 0.5)))
        
        # Select key sentences
        selected_indices = self._select_key_sentences(
            sentences, sentence_scores, target_sentences
        )
        
        # Get selected sentences
        selected_sentences = [sentences[i] for i in selected_indices]
        
        # Apply compression to longer sentences
        compressed_sentences = []
        for sentence in selected_sentences:
            # Apply more aggressive compression to longer sentences
            if len(sentence.split()) > 15:
                compressed = self._compress_sentence(sentence, aggressive=True)
            elif len(sentence.split()) > 10:
                compressed = self._compress_sentence(sentence, aggressive=False)
            else:
                compressed = sentence  # No compression for short sentences
            
            compressed_sentences.append(compressed)
        
        # Enhance flow with appropriate connectors
        enhanced_sentences = self._enhance_flow(compressed_sentences)
        
        # Join sentences into summary
        summary = ' '.join(enhanced_sentences)
        
        # Apply final enhancements
        summary = self._enhance_final_summary(summary)
        
        return summary
    
    def summarize(self, text: str, compression_ratio: float = 0.5) -> str:
        """
        Generate a summary of the input text using our neural-guided approach
        
        Args:
            text: Text to summarize
            compression_ratio: Target ratio of summary size to original text
        
        Returns:
            A coherent, well-formed summary
        """
        if not text or len(text.strip()) == 0:
            return "Empty text provided."
        
        try:
            # Generate the summary
            summary = self._generate_summary_structure(text, compression_ratio)
            
            # Return the final summary
            return summary
            
        except Exception as e:
            logger.error(f"Error in summarization: {e}")
            # Fallback to simple extraction of first sentence
            sentences = self._segment_text(text)
            return sentences[0] if sentences else "Summarization failed."


# Helper function for integration with IndicSummarizer
def generate_neural_summary(text: str, lang_code: str = 'te', **kwargs) -> str:
    """
    Generate a neural summary for the given text and language code (stub implementation).
    """
    # Stub implementation: return the first sentence
    if not text or not text.strip():
        return ''
    sentences = text.split('.')
    return sentences[0] + ('.' if sentences[0] else '')


def generate_neural_summary(text: str, lang: str = 'te', 
                           model_dir: str = None, 
                           config_path: str = None,
                           compression_ratio: float = 0.5,
                           **kwargs) -> str:
    """
    Generate a neural-guided summary for the given text
    
    This function is the main entry point for generating summaries with the
    neural summarizer. It handles locating model files and configuration,
    and gracefully falls back to rule-based summarization if model loading fails.
    
    Args:
        text: Text to summarize
        lang: Language code ('te' for Telugu, 'hi' for Hindi)
        model_dir: Path to the model directory (optional, will use default if None)
        config_path: Path to the model config (optional, will use default if None)
        compression_ratio: Target ratio of summary to original text (0.0-1.0)
    
    Returns:
        A coherent summary of the text
    """
    try:
        # Get default paths if not provided
        if not model_dir or not config_path:
            base_dir = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            model_dir = model_dir or str(base_dir / "models" / "final_model")
            config_path = config_path or str(base_dir / "configs" / "model_config.json")
            
            # Verify paths exist
            if not Path(model_dir).exists():
                logger.warning(f"Default model directory not found: {model_dir}")
                logger.warning("Using rule-based summarization only")
                
            if not Path(config_path).exists():
                logger.warning(f"Default config path not found: {config_path}")
                logger.warning("Using rule-based summarization only")
        
        # Initialize the summarizer
        summarizer = NeuralSummarizer(
            model_path=model_dir,
            config_path=config_path,
            lang_code=lang
        )
        
        # Generate the summary
        summary = summarizer.summarize(text, compression_ratio)
        return summary
        
    except Exception as e:
        logger.error(f"Error in neural summarization: {e}")
        logger.error("Falling back to basic summarization")
        
        # Extremely simple fallback - just return the first 1-2 sentences
        sentences = re.split(r'(?<=[.!?।॥])\s+', text)
        if not sentences:
            return "Summarization failed."
        
        # Return first sentence for very short texts, or first two for longer ones
        if len(sentences) <= 3:
            return sentences[0]
        else:
            return ' '.join(sentences[:2])


if __name__ == "__main__":
    # Example usage with Telugu text (from the user's query)
    te_text = """ప్రస్తుతం భారత్‌-పాకిస్తాన్ మధ్య పరిస్థితి మరింత ఉద్రిక్తంగా మారుతున్నది. కశ్మీర్ సరిహద్దుల్లో తరచూ కాల్పులు జరగడం, ఉగ్రవాద చర్యలు కొనసాగడం ఈ ఉద్రిక్తతకు ప్రధాన కారణాలు. ఇటీవలి కాలంలో పాక్ మద్దతు ఉన్న ఉగ్రవాదుల చొరబాటు ప్రయత్నాలు పెరిగినట్లు భారత సైన్యం పేర్కొంది. అదే సమయంలో, రాజకీయ నేతల మధ్య మాటల యుద్ధం కూడా తీవ్రంగా సాగుతోంది. ఇరు దేశాల ప్రజలు శాంతిని కోరుతున్నా, సరిహద్దుల్లో పరిస్థితి ఇంకా గందరగోళంగా ఉంది. ఈ పరిస్థితిని చర్చల ద్వారా పరిష్కరించాలనే సూచనలు అంతర్జాతీయంగా వెల్లువెత్తుతున్నాయి."""
    
    # Reference summary (from the user's query)
    te_reference = """భారత్‌-పాకిస్తాన్ మధ్య ఉద్రిక్తతలు పెరిగుతున్నాయి. కశ్మీర్ సరిహద్దుల్లో కాల్పులు, ఉగ్రవాద చర్యలు ప్రధాన కారణాలు కాగా, పాక్ మద్దతు ఉన్న చొరబాట్లు కూడా పెరుగుతున్నాయి. రాజకీయ స్థాయిలో మాటల యుద్ధం జరుగుతోంది. ప్రజలు శాంతిని కోరుతున్నా, పరిస్థితి ఇంకా అస్తవ్యస్థంగా ఉంది. సమస్యను చర్చల ద్వారా పరిష్కరించాలని అంతర్జాతీయ సమాజం సూచిస్తోంది."""
    
    # Generate and print the summary
    te_summary = generate_neural_summary(te_text, 'te')
    print("Telugu text:")
    print(te_text)
    print("\nReference summary:")
    print(te_reference)
    print("\nGenerated summary:")
    print(te_summary)
    
    # Example Hindi text (Kashmir conflict example)
    hi_text = """भारत और पाकिस्तान के बीच तनाव बढ़ रहा है। कश्मीर सीमा पर लगातार गोलीबारी और आतंकवादी गतिविधियां जारी हैं। भारतीय सेना के अनुसार, हाल के दिनों में पाकिस्तान समर्थित आतंकवादियों की घुसपैठ की कोशिशों में वृद्धि हुई है। इसी समय, राजनीतिक नेताओं के बीच वाक्युद्ध भी तेज है। दोनों देशों के लोग शांति चाहते हैं, लेकिन सीमा पर स्थिति अभी भी अस्थिर है। इस स्थिति को वार्ता के माध्यम से सुलझाने के सुझाव अंतरराष्ट्रीय स्तर पर दिए जा रहे हैं।"""
    
    # Reference summary for Hindi
    hi_reference = """भारत-पाकिस्तान के बीच तनाव बढ़ रहा है। कश्मीर सीमा पर गोलीबारी और आतंकवादी गतिविधियां जारी हैं। भारतीय सेना ने पाकिस्तान समर्थित आतंकवादियों की घुसपैठ में वृद्धि की बात कही है। राजनीतिक नेताओं के बीच वाक्युद्ध भी तेज है। लोग शांति चाहते हैं, पर स्थिति अस्थिर है। अंतरराष्ट्रीय स्तर पर वार्ता द्वारा समाधान के सुझाव दिए जा रहे हैं।"""
    
    # Generate and print the Hindi summary
    hi_summary = generate_neural_summary(hi_text, 'hi')
    print("\n\nHindi text:")
    print(hi_text)
    print("\nReference summary:")
    print(hi_reference)
    print("\nGenerated summary:")
    print(hi_summary)